class TechVetMap:

    DRIVETRAIN_LEFT_FWD = 22
    DRIVETRAIN_LEFT_BKWD = 23

    DRIVETRAIN_LEFT_PWM = 0


    DRIVETRAIN_RIGHT_FWD = 27
    DRIVETRAIN_RIGHT_BKWD = 17

    DRIVETRAIN_RIGHT_PWM = 1

