class TechVetMap:

    DRIVETRAIN_RIGHT_FWD = 23
    DRIVETRAIN_RIGHT_BKWD = 17

    DRIVETRAIN_LEFT_PWM = 0

    DRIVETRAIN_LEFT_FWD = 22
    DRIVETRAIN_LEFT_BKWD = 27

    DRIVETRAIN_RIGHT_PWM = 1

