class BotPacket:
    CLI_INPUT_MODE = 0x01
    TELEOP_INPUT_MODE = 0x02

    HECTOR_MODE_DISABLED = 0x00
    HECTOR_MODE_AUTO = 0x01
    HECTOR_MODE_TELEOP = 0x02

    JOYSTICK_RESERVE_START = 3
    JOYSTICK_RESERVE_END = 24

    CLIENT_ID_BYTE = 0

    HECTOR_MODE_BYTE = 1
    INPUT_MODE_BYTE = 2

    JOYSTICK_LEFT_Y = 4
    JOYSTICK_LEFT_X = 5

    JOYSTICK_RIGHT_Y = 6
    JOYSTICK_RIGHT_X = 7

    HAT_BUTTON = 8
